//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicEntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_UserDetail
    {
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string UserFunc { get; set; }
        public byte[] UserPicture { get; set; }
        public bool Show { get; set; }
    }
}
